plot names are stored in hash values and not in the keys which store …
solgenomics/sgn pull request #3283
Opened 2021-01-15 20:10 UTC by nmenda

…the row indices

Description 
-----------------------------------------------------

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [ ] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] New feature
  - [ ] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.
  - [ ] Any new _legacy_ JavaScript has been moved from `/js` to `/js/source/legacy`.

2021-01-19 22:55 UTC, bellerbrock requested changes
Nice find Naama. I'd suggest fixing this problem at it's source on line [356](https://github.com/solgenomics/sgn/blob/dcfd0e7eb43cbb648631aa0c53a47c7daffc00dc/lib/CXGN/Trial/ParseUpload/Plugin/MultipleTrialDesignExcelFormat.pm#L356) though.

Changing 
```
    else {
        $plot_name =~ s/^\s+|\s+$//g; #trim whitespace from front and end...
        if ($seen_plot_names{$plot_name}) {
            push @error_messages, "Cell M$row_name: duplicate plot name <b>$plot_name</b> at cell A".$seen_plot_names{$plot_name}.".";
        }
        $seen_plot_names{$row_name}=$plot_name;
    }
```
to something like 
```
    else {
        $plot_name =~ s/^\s+|\s+$//g; #trim whitespace from front and end...
        if ($seen_plot_names{$plot_name}) {
            push @error_messages, "Cell M$row_name: duplicate plot name <b>$plot_name</b> seen before at cell M".$seen_plot_names{$plot_name}.".";
        }
        $seen_plot_names{$plot_name}=$row_name;
    }
```
would fix the downstream problem you encountered and also fix the validator's reporting of duplicates found in the upload file.

2021-01-20 18:21 UTC, lukasmueller submitted a review, later dismissed

2021-01-21 16:08 UTC, lukasmueller approved these changes
:-)

2021-01-21 16:09 UTC, bellerbrock approved these changes

2021-01-21 16:11 UTC, merged