Topic/add genotype project views
solgenomics/sgn pull request #3636
Opened 2021-07-27 19:58 UTC by dwaring87

Description 
-----------------------------------------------------

This PR adds a DB patch that:
- adds a genotyping_project_id column to the materialized_genoview matview
- creates the genotyping_projects view
- creates the various genotyping_projects binary views

Since the materialized_genoview had to be deleted in order to add the new column, and the removal cascades to many other views, the db patch recreates all of the binary views based on the previous `SpeedUpMatViews` DB patch.

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [ ] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] New feature
  - [ ] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.
  - [ ] Any new _legacy_ JavaScript has been moved from `/js` to `/js/source/legacy`.

2021-07-29 20:36 UTC, bellerbrock requested changes
Hey @dwaring87, the materialized_genoview update and genotyping_project binary views look good!

The other sql for the materialized phenoview and all the other binary views should not be necessary though, I'd remove that before merging the patch

2021-08-02 12:04 UTC, dwaring87 commented
@bellerbrock Thanks for looking this over.  Since I had to add a column to the materialized_genoview matview, that matview had to be dropped first and this cascaded to a bunch of the binary views.  So many of the binary views had to be recreated after recreating the materialized_genoview.  The phenoview isn't necessary but I thought it might be good to have one patch with all of the definitions in it?  If you think it's better to remove it, I can do that.

2021-08-04 16:26 UTC, bellerbrock approved these changes

2021-08-05 15:24 UTC, lukasmueller approved these changes
:-)

2021-08-05 15:24 UTC, merged