Topic/solgs/refactor jan23
solgenomics/sgn pull request #4426
Opened 2023-02-07 11:33 UTC by isaak

Description 
-----------------------------------------------------

-- reorganize, rename, clean up solgs mason components

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [ ] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] New feature
  - [ ] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.
  - [ ] Any new _legacy_ JavaScript has been moved from `/js` to `/js/source/legacy`.

2023-02-07 19:33 UTC, alockrow requested changes
Found one typo, otherwise looks good!

2023-02-07 19:33 UTC, alockrow commented on mason/solgs/tools/cluster/index.mas
> +<!-- <& /solgs/genotyping_protocol/inde.mas &> -->
This looks like a typo!
```suggestion
<!-- <& /solgs/genotyping_protocol/index.mas &> -->
```

2023-02-09 16:17 UTC, alockrow approved these changes
:-)

2023-02-12 02:08 UTC, lukasmueller approved these changes
:-)

2023-02-12 02:08 UTC, merged