Show non numeric traits and trait raw data on trait detail page
solgenomics/sgn pull request #4739
Opened 2023-11-27 14:45 UTC by lukasmueller

Description 
-----------------------------------------------------

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [ ] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] New feature
  - [ ] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.
  - [ ] Any new _legacy_ JavaScript has been moved from `/js` to `/js/source/legacy`.

2023-12-01 20:07 UTC, alockrow requested changes
Looks good except for raw being written twice in the section description. I also wasn't able to find any non-numeric data to test it on. Also of note: the smiley shows up while the page is loading; not sure if that matters at all.

2023-12-01 20:07 UTC, alockrow commented on mason/breeders_toolbox/trial.mas
Raw is written twice in the section description: "View raw phenotype raw data"

2023-12-09 08:08 UTC, lukasmueller commented on mason/breeders_toolbox/trial.mas
Thank you for catching this, fixed!

2023-12-09 08:09 UTC, lukasmueller commented
I think I fixed the issue with the limited traits in the menu by moving the pageSize argument to the correct location in the ajax call.

2023-12-21 17:25 UTC, darekbienkowski approved these changes
;-)

2024-01-04 18:25 UTC, nmenda approved these changes

2024-01-04 18:25 UTC, nmenda commented on mason/breeders_toolbox/trial/trial_raw_data.mas
> +<div id="trait_selector_for_raw_data">:-)</div><br />
maybe replace this with "Loading..." ?

2024-01-09 04:19 UTC, merged