added an email option to accession upload
solgenomics/sgn pull request #5007
Opened 2024-07-11 13:17 UTC by Sri-2023

Description 
-----------------------------------------------------

Also, will resolve #4729

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [ ] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] New feature
  - [ ] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.
  - [ ] Any new _legacy_ JavaScript has been moved from `/js` to `/js/source/legacy`.

2024-07-12 17:31 UTC, Sri-2023 commented
@dwaring87, thank you for testing and providing feedback. I will fix the issue soon. Earlier, was able to upload accessions being on the master. However, after performing a git pull, am unable to upload accessions. I'm encountering a long error message,
![Screenshot from 2024-07-12 13-19-05](https://github.com/user-attachments/assets/d53aced4-e913-42b5-8aa4-c670e6199328)

2024-07-12 19:34 UTC, Sri-2023 commented
Thank you @dwaring87 for fixing the bug. It works now..

2024-07-15 14:08 UTC, dwaring87 approved these changes
@Sri-2023 Thanks for the updates!

2024-07-16 18:19 UTC, dwaring87 commented on mason/breeders_toolbox/manage_accessions.mas
> +$email_address => ""
this is not needed

2024-07-16 18:19 UTC, dwaring87 commented on mason/breeders_toolbox/trialtreefolders.mas
> +$email_address => ""
this is not needed

2024-07-16 18:19 UTC, dwaring87 commented on mason/breeders_toolbox/trialtreefolders.mas
> +<& /breeders_toolbox/add_accessions_dialogs.mas, preferred_species=>$preferred_species, editable_stock_props=>$editable_stock_props, editable_stock_props_definitions=>$editable_stock_props_definition
email_address argument is not needed

2024-07-17 13:10 UTC, dwaring87 approved these changes
👍🏽

2024-07-18 14:47 UTC, lukasmueller commented
I think the initial check should also be reported by email, as the check can take longer than the actual upload and time out.

2024-07-18 14:48 UTC, lukasmueller reviewed
The check results should also go through email? The check can take a long time and time out

2024-07-19 20:19 UTC, lukasmueller requested changes
The email could cotnain a link to each accession uploaded (maybe with a cutoff if there are more than a thousand or so). What do you think?

2024-08-01 20:47 UTC, dwaring87 commented
One minor issue: If I choose cancel on the confirmation dialog asking if I want to continue and receive an email, the accessions are still saved and I still get an email.  I doubt anyone would get that far and cancel at that point, but if I did, I would expect it not to proceed with saving.

2024-08-01 20:47 UTC, dwaring87 approved these changes

2024-08-02 18:49 UTC, lukasmueller approved these changes
:-)

2024-08-02 18:49 UTC, merged