Generic seedlot upload
solgenomics/sgn pull request #5056
Opened 2024-08-09 18:39 UTC by titima15

Description 
-----------------------------------------------------

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [ ] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] New feature
  - [ ] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.
  - [ ] Any new _legacy_ JavaScript has been moved from `/js` to `/js/source/legacy`.

2024-08-15 18:20 UTC, titima15 commented
@dwaring87 I don't see the comment that you mentioned in the lab meeting.

2024-08-15 18:33 UTC, dwaring87 requested changes

2024-08-15 18:33 UTC, dwaring87 commented
@titima15 How about now?  I guess I need to submit the review before you can see the comments...

2024-08-15 18:35 UTC, dwaring87 commented on lib/CXGN/Stock/Seedlot/ParseUpload/Plugin/SeedlotFromAccessionGeneric.pm
> +        if ($duplicated_seedlot_names{$seedlot_name}) {
The same applies to the other plugin

2024-08-15 19:20 UTC, titima15 commented on lib/CXGN/Stock/Seedlot/ParseUpload/Plugin/SeedlotFromAccessionGeneric.pm
> +        if ($duplicated_seedlot_names{$seedlot_name}) {
oops, I forgot. Thanks. I already fixed.

2024-08-19 13:25 UTC, dwaring87 approved these changes
Thanks!

2024-09-05 14:05 UTC, lukasmueller approved these changes
:-)

2024-09-05 15:41 UTC, merged