Show analyses on dataset details page
solgenomics/sgn pull request #5215
Opened 2024-11-19 19:52 UTC by ryan-preble

Description 
-----------------------------------------------------

Stored analyses that use a dataset will now be listed on the dataset details page. Likewise, the stored analysis details page now links to the dataset details page. 

#5154 

Checklist 
---------------------------------------------------------------------------------------
- [ ] Refactoring only
- [ ] Documentation only
- [ ] Fixture update only
- [ ] Bug fix
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] New feature
  - [ ] Relevant tests have been created and run.
  - [ ] Data was added to the fixture
    - [ ] Data was added via a patch in `/t/data/fixture/patches/`.
  - [ ] User-Facing Change
    - [ ] The user manual in `/docs` has been updated.
  - [ ] Any new Perl has been documented using **perldoc**.
  - [ ] Any new JavaScript has been documented using **JSDoc**.
  - [ ] Any new _legacy_ JavaScript has been moved from `/js` to `/js/source/legacy`.

2024-12-05 22:09 UTC, alockrow approved these changes

2024-12-09 16:20 UTC, lukasmueller requested changes

2024-12-09 17:39 UTC, ryan-preble commented on lib/CXGN/Dataset.pm
> +    my $analysis_q = "select DISTINCT project.name, project.project_id FROM nd_experiment_project
See https://github.com/solgenomics/sgn/pull/5215/commits/d30ed57472b50b609a636ecffe86009e9ccb7f26

2025-01-09 14:16 UTC, lukasmueller approved these changes
:-)

2025-01-09 16:40 UTC, merged